version: '3.1'
services:
    consul-server:
        hostname: consul-server
        build: consul-server
        ports:
            - "8300:8300"
            - "8301:8301"
            - "8302:8302"
            - "8500:8500"
            - "8600:8600"
        restart: always
    nginx:
        hostname: nginx
        build: nginx
        ports:
            - "80:80"
        links:
            - consul-server
    php-fpm:
        hostname: php-fpm
        build: php-fpm
#        ports:
#            - "9000:9000"
        links:
            - consul-server

